# LSTM(Long Short Term Memory) Implementation

In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, LSTM, Embedding

In [2]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words = 10000)    # num_words = embedding vector size(always)

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [3]:
X_train.shape, X_test.shape

((25000,), (25000,))

In [4]:
X_train[0]                # already vectors are given in imdb dataset instead of raw text

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 5535,
 18,

In [5]:
# Apply pad sequences

X_train = pad_sequences(X_train, maxlen = 600, padding = 'post')
X_test = pad_sequences(X_test, maxlen = 600, padding = 'post')

In [6]:
X_train[0]

array([   1,   14,   22,   16,   43,  530,  973, 1622, 1385,   65,  458,
       4468,   66, 3941,    4,  173,   36,  256,    5,   25,  100,   43,
        838,  112,   50,  670,    2,    9,   35,  480,  284,    5,  150,
          4,  172,  112,  167,    2,  336,  385,   39,    4,  172, 4536,
       1111,   17,  546,   38,   13,  447,    4,  192,   50,   16,    6,
        147, 2025,   19,   14,   22,    4, 1920, 4613,  469,    4,   22,
         71,   87,   12,   16,   43,  530,   38,   76,   15,   13, 1247,
          4,   22,   17,  515,   17,   12,   16,  626,   18,    2,    5,
         62,  386,   12,    8,  316,    8,  106,    5,    4, 2223, 5244,
         16,  480,   66, 3785,   33,    4,  130,   12,   16,   38,  619,
          5,   25,  124,   51,   36,  135,   48,   25, 1415,   33,    6,
         22,   12,  215,   28,   77,   52,    5,   14,  407,   16,   82,
          2,    8,    4,  107,  117, 5952,   15,  256,    4,    2,    7,
       3766,    5,  723,   36,   71,   43,  530,  4

In [7]:
X_train.shape, X_test.shape

((25000, 600), (25000, 600))

# LSTM model Implementation

In [8]:
model = Sequential()
model.add(Embedding(10000, output_dim = 2, input_length = 600))
model.add(LSTM(32, return_sequences = False))
model.add(Dense(1, activation = 'sigmoid'))
model.build(input_shape = (None, 600))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 600, 2)         │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 32)             │         4,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 24,513 (95.75 KB)

 Trainable params: 24,513 (95.75 KB)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
history = model.fit(X_train, y_train, epochs = 5, validation_data= (X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 25s 28ms/step - accuracy: 0.5011 - loss: 0.6933 - val_accuracy: 0.5000 - val_loss: 0.6931
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 26ms/step - accuracy: 0.5079 - loss: 0.6927 - val_accuracy: 0.5027 - val_loss: 0.6930
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 27ms/step - accuracy: 0.5073 - loss: 0.6901 - val_accuracy: 0.5052 - val_loss: 0.6905
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 27ms/step - accuracy: 0.5104 - loss: 0.6857 - val_accuracy: 0.5083 - val_loss: 0.6898
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 27ms/step - accuracy: 0.5225 - loss: 0.6799 - val_accuracy: 0.5116 - val_loss: 0.6893


In [14]:
# for easy understanding, we will just take tkae first 60 numbers from the text-vetor intead of 600
test_data = X_test[0][0:50].reshape(1,-1)
test_data

array([[   1,  591,  202,   14,   31,    6,  717,   10,   10,    2,    2,
           5,    4,  360,    7,    4,  177, 5760,  394,  354,    4,  123,
           9, 1035, 1035, 1035,   10,   10,   13,   92,  124,   89,  488,
        7944,  100,   28, 1668,   14,   31,   23,   27, 7479,   29,  220,
         468,    8,  124,   14,  286,  170]], dtype=int32)

In [18]:
test_data2 = X_test[1][0:100].reshape(1,-1)
test_data2

array([[   1,   14,   22, 3443,    6,  176,    7, 5063,   88,   12, 2679,
          23, 1310,    5,  109,  943,    4,  114,    9,   55,  606,    5,
         111,    7,    4,  139,  193,  273,   23,    4,  172,  270,   11,
        7216,    2,    4, 8463, 2801,  109, 1603,   21,    4,   22, 3861,
           8,    6, 1193, 1330,   10,   10,    4,  105,  987,   35,  841,
           2,   19,  861, 1074,    5, 1987,    2,   45,   55,  221,   15,
         670, 5304,  526,   14, 1069,    4,  405,    5, 2438,    7,   27,
          85,  108,  131,    4, 5045, 5304, 3884,  405,    9, 3523,  133,
           5,   50,   13,  104,   51,   66,  166,   14,   22,  157,    9,
           4]], dtype=int32)

In [16]:
y_pred = model.predict(test_data)     # predicting for just 1 review for first 50 words in it.
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step


array([[0.3551923]], dtype=float32)

In [17]:
X_test.shape

(25000, 600)

In [19]:
y_pred2 = model.predict(test_data2)     # predicting for just 1 review for first 50 words in it.
y_pred2

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step


array([[0.85246235]], dtype=float32)

In [20]:
# prediction for whole test dataset
y_pr = model.predict(X_test)
y_pr

782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step


array([[0.46904343],
       [0.46904343],
       [0.95900875],
       ...,
       [0.46904343],
       [0.46904343],
       [0.46904343]], dtype=float32)

In [21]:
import numpy as np
y_pred_tr = np.argmax(y_pr, axis = 1)
y_pred_tr

array([0, 0, 0, ..., 0, 0, 0])

In [22]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred_tr)
ac_sc = accuracy_score(y_test, y_pred_tr)
cl_report = classification_report(y_test, y_pred_tr)

print("Confusion matrix: \n", cm)
print("\nAccuracy score: ", ac_sc)
print("\nClassification report: \n", cl_report)

Confusion matrix: 
 [[12500     0]
 [12500     0]]

Accuracy score:  0.5

Classification report: 
               precision    recall  f1-score   support

           0       0.50      1.00      0.67     12500
           1       0.00      0.00      0.00     12500

    accuracy                           0.50     25000
   macro avg       0.25      0.50      0.33     25000
weighted avg       0.25      0.50      0.33     25000



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
