# Implementation of Perceptron

In [28]:
import numpy as np
import pandas as pd

In [2]:
np.random.randn(3)

array([-0.85176044, -1.49931401, -0.41572757])

In [17]:
class Perceptron:

  def __init__(self, eta, epochs):
    self.weights = np.random.randn(3) * 1e-4
    self.eta = eta                              # learning rate
    self.epochs = epochs                        # n(iterations)
    print(f"weights: {self.weights}")


  def activationFunction(self, inputs, weights):
    LC = np.dot(inputs, weights)
    return np.where(LC > 0, 1, 0)


  def predict(self, X):
    X_with_bias = np.c_[X, -np.ones((len(X), 1))]
    return self.activationFunction(X_with_bias, self.weights)


  def fit(self, X, y):
    self.X = X
    self.y = y

    X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
    print(f"X_with_bias: \n{X_with_bias}")

    for iter in range(self.epochs):
      print(f"For epoch {iter}")
      y_tar = self.activationFunction(X_with_bias, self.weights)
      print(f"Predicted value: \n{y_tar}")
      error = self.y - y_tar          # (actual - predicted)
      print(f"Error: \n{error}")

      # Applying "Weight Updation formula"
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
      print(f"Updated weights: \n{self.weights}")



## AND Gate with Perceptron

In [4]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,0,0,1]}

AND_df = pd.DataFrame(data)
AND_df

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [5]:
X = AND_df.drop("y", axis = 1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [6]:
y = AND_df["y"]
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [18]:
model = Perceptron(eta = 0.5, epochs = 10)

weights: [-3.00568945e-05 -4.29622398e-05 -8.07590327e-05]


In [19]:
model

In [20]:
model.fit(X, y)

X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
For epoch 0
Predicted value: 
[1 1 1 1]
Error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights: 
[-0.50003006 -0.50004296  1.49991924]
For epoch 1
Predicted value: 
[0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights: 
[-3.00568945e-05 -4.29622398e-05  9.99919241e-01]
For epoch 2
Predicted value: 
[0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights: 
[0.49996994 0.49995704 0.49991924]
For epoch 3
Predicted value: 
[0 1 1 1]
Error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights: 
[-3.00568945e-05 -4.29622398e-05  1.49991924e+00]
For epoch 4
Predicted value: 
[0 0 0 0]
Error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights: 
[0.49996994 0.49995704 0.99991924]
For epoch 5
Predicted value: 
[0 0 0 1]
Error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights: 
[0.49996994 0.4999570

In [21]:
model.predict(X)

array([0, 0, 0, 1])

In [23]:
model.weights     # Final weights are decieded after getting error = 0

array([0.49996994, 0.49995704, 0.99991924])

**NOTE:** Similarly, OR gate can be implemented and we can see error = 0 after some iterations. So, here we get our model predictions correct.

## Implementation of XOR gate.

In [24]:
XOR = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,1,1,0]}

XOR_df = pd.DataFrame(XOR)
XOR_df

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [26]:
X = XOR_df.drop("y", axis = 1)
y = XOR_df["y"]

In [25]:
model = Perceptron(eta = 0.5, epochs = 100)

weights: [-1.10967174e-04 -1.08726281e-04 -8.26473706e-05]


In [27]:
model.fit(X, y)

X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
For epoch 0
Predicted value: 
[1 0 0 0]
Error: 
0   -1
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: 
[ 0.49988903  0.49989127 -0.50008265]
For epoch 1
Predicted value: 
[1 1 1 1]
Error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: 
[-1.10967174e-04 -1.08726281e-04  4.99917353e-01]
For epoch 2
Predicted value: 
[0 0 0 0]
Error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: 
[ 0.49988903  0.49989127 -0.50008265]
For epoch 3
Predicted value: 
[1 1 1 1]
Error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: 
[-1.10967174e-04 -1.08726281e-04  4.99917353e-01]
For epoch 4
Predicted value: 
[0 0 0 0]
Error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
Updated weights: 
[ 0.49988903  0.49989127 -0.50008265]
For epoch 5
Predicted value: 
[1 1 1 1]
Error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
Updated weights: 
[-1.10967174e-0

**NOTE:** Here, we can see that even after 100th iteration, we still get error in predicting XOR output corretly.

It shows that how Perceptron can only perform simple tasks correctly and a complex task cannot be performed by it.

As in later lectures, we can see that how a Perceptron can also perform complex tasks effectively.