# Tensorflow Implementation

In [102]:
import tensorflow as tf

print("Tensorflow version: {}".format(tf.__version__))
print("Eager execution: {}".format(tf.executing_eagerly()))
print("Keras version: {}".format(tf.keras.__version__))

Tensorflow version: 2.18.0
Eager execution: True
Keras version: 3.8.0


In [103]:
if tf.test.is_gpu_available():
    print("Running on GPU")
else:
    print("Running on CPU")


Running on CPU


In [104]:
tf.config.list_physical_devices('CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [105]:
tf.config.list_physical_devices('GPU')

[]

# Tensor constant

In [106]:
num = tf.constant(42)

In [107]:
num

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [108]:
num.numpy()

np.int32(42)

In [109]:
num1 = tf.constant(1, dtype = tf.int64)
num1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [110]:
num_array = tf.constant([[10,20] , [30,40]])
print(num_array)

tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [111]:
num_array.numpy()

array([[10, 20],
       [30, 40]], dtype=int32)

# To make arrays of 0s and 1s

In [112]:
print(tf.ones(shape = (2, 3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [113]:
print(tf.zeros(shape = (3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [114]:
cons1 = tf.constant([[1, 2, 3], [4, 5, 6]])
cons2 = tf.constant([[10, 20, 30], [40, 50, 60]])
result = tf.add(cons1, cons2)

print(result)

tf.Tensor(
[[11 22 33]
 [44 55 66]], shape=(2, 3), dtype=int32)


# Random constant

In [115]:
tf.random.normal(shape = (2,2), mean= 0, stddev = 1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.8384007 , -0.47512755],
       [ 0.38359565, -0.74579424]], dtype=float32)>

In [116]:
tf.random.uniform(shape = (3, 3), minval= 0, maxval = 10, dtype = tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [2, 1, 6],
       [5, 0, 0]], dtype=int32)>

## Variables

In [117]:
var = 33
var0 = tf.Variable(42)      # Rank0 tensor
var3 = tf.Variable([ [ [1,2,100], [3,4,200] ], [ [5,6,300],[7,8,400] ] ])     # Rank3 tensor

In [118]:
print("Python variable: ", var)
print("\nRank0 variable: ", var0)
print("\nRank3 variable: ", var3)

Python variable:  33

Rank0 variable:  <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>

Rank3 variable:  <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[  1,   2, 100],
        [  3,   4, 200]],

       [[  5,   6, 300],
        [  7,   8, 400]]], dtype=int32)>


## Explicitly satisfying the datatype

In [119]:
float_var64 = tf.Variable(100, dtype = tf.float64)
float_var64.dtype

tf.float64

## Reassigning a variable

In [120]:
var1 = tf.Variable(100)
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>

In [121]:
var1.assign(200)
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=200>

In [122]:
initital_val = tf.random.normal(shape = (2,3))
print(initital_val)

a = tf.Variable(initital_val)
print(a)

tf.Tensor(
[[ 0.345975   -0.7813318  -2.1645963 ]
 [ 0.44911915  1.5323876   1.3402948 ]], shape=(2, 3), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 0.345975  , -0.7813318 , -2.1645963 ],
       [ 0.44911915,  1.5323876 ,  1.3402948 ]], dtype=float32)>


NOTE: We can assign "=" with assign(value) or assign_add(value) with "+=" or assign_sub(value) with "-="

In [123]:
new_val = tf.random.normal(shape=(2,3))
a.assign(new_val)

for i in range(2):
  for j in range(2):
    assert a[i,j] == new_val[i,j]

# Shaping a tensor

In [124]:
tensor = tf.Variable([ [ [1 ,2, 100], [3, 4, 200] ], [ [5, 6, 300], [7, 8, 400] ] ])
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[  1,   2, 100],
        [  3,   4, 200]],

       [[  5,   6, 300],
        [  7,   8, 400]]], dtype=int32)>

In [125]:
tensor.shape

TensorShape([2, 2, 3])

NOTE: Tensors may be reshaped and retain the same values, as is often required for constructing neural networks.

In [126]:
tensor1 = tf.reshape(tensor, [1, 12]) # one row, 8 columns
tensor1

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=
array([[  1,   2, 100,   3,   4, 200,   5,   6, 300,   7,   8, 400]],
      dtype=int32)>

In [127]:
tensor2 = tf.reshape(tensor, [3, 4])
tensor2

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[  1,   2, 100,   3],
       [  4, 200,   5,   6],
       [300,   7,   8, 400]], dtype=int32)>

# Rank of a tensor

No. of dimensions it has. i. e. the number of indices that are required to specify any particular element of that tensor.

In [128]:
tf.rank(tensor)
# the shape =() because the O/P here is a scaler value

<tf.Tensor: shape=(), dtype=int32, numpy=3>

# Specifying an element of a tensor

In [129]:
tensor3 = tensor[1, 0, 1]
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=6>

# Casting a tensor to a Numpy / Python variable

In [130]:
print(tensor.numpy())

[[[  1   2 100]
  [  3   4 200]]

 [[  5   6 300]
  [  7   8 400]]]


In [131]:
print(tensor[1, 0, 1].numpy())

6


# Finding the size of a tensor

In [132]:
tf.size(input = tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [133]:
tf.size(input = tensor).numpy()

np.int32(12)

# Datatype of a tensor

In [134]:
tensor2

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[  1,   2, 100,   3],
       [  4, 200,   5,   6],
       [300,   7,   8, 400]], dtype=int32)>

In [135]:
tensor2.dtype

tf.int32

# Tensorflow Mathematical operations

Can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU.

In [136]:
a = tf.random.normal(shape = (2,2))
b = tf.random.normal(shape = (2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)

print("a -> ", a)
print("\nb -> ", b)
print("\nc -> ", c)
print("\nd -> ", d)
print("\ne -> ", e)



a ->  tf.Tensor(
[[-0.6373305  2.7589011]
 [ 1.026495   3.3563783]], shape=(2, 2), dtype=float32)

b ->  tf.Tensor(
[[ 2.1393998  1.7028176]
 [-1.4468794  1.5833094]], shape=(2, 2), dtype=float32)

c ->  tf.Tensor(
[[ 1.5020692  4.4617186]
 [-0.4203844  4.9396877]], shape=(2, 2), dtype=float32)

d ->  tf.Tensor(
[[ 2.256212   19.906933  ]
 [ 0.17672305 24.400515  ]], shape=(2, 2), dtype=float32)

e ->  tf.Tensor(
[[  4.4909725  86.63627  ]
 [  0.6567943 139.72661  ]], shape=(2, 2), dtype=float32)


# Performing element-wise primitive tensor operations

In [137]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[  1,   2, 100],
        [  3,   4, 200]],

       [[  5,   6, 300],
        [  7,   8, 400]]], dtype=int32)>

In [138]:
tensor * tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[     1,      4,  10000],
        [     9,     16,  40000]],

       [[    25,     36,  90000],
        [    49,     64, 160000]]], dtype=int32)>

In [139]:
tensor - tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int32)>

# Broadcasting

Element -wise tensor operations support broadcasting in the same way that Numpy arrays do.

The simplest example is that of multiplying a tensor by a scaler.

In [140]:
tensor4 = tensor * 4
tensor4

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[   4,    8,  400],
        [  12,   16,  800]],

       [[  20,   24, 1200],
        [  28,   32, 1600]]], dtype=int32)>

# Transpose Matrix multiplication

In [141]:
matrix_u = tf.constant([[3,4,3]])
matrix_v = tf.constant([[1,2,1]])

tf.matmul(matrix_u, tf.transpose(a = matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

# Casting a Tensor to another (tensor) datatype

In [142]:
i = tf.cast(tensor1, dtype = tf.float64)
i

<tf.Tensor: shape=(1, 12), dtype=float64, numpy=
array([[  1.,   2., 100.,   3.,   4., 200.,   5.,   6., 300.,   7.,   8.,
        400.]])>

# With truncation

In [143]:
j = tf.cast(tf.constant(5.332423), dtype = tf.int64)
j

<tf.Tensor: shape=(), dtype=int64, numpy=5>

# Declaring Ragged tensors

A ragged tensor is a tensor with on eor more rageed dimensions.

Rageed dimensions are dimensions that have slices that may have differernt lengths.

There are a variety of methods for declaring ragged arrays, the simplest being a constant ragged array.


In [144]:
# Declaring a constatn ragged array and the lengths of the individual slices

ragged = tf.ragged.constant([ [1,2,3,4], [], [5,6,7], [8], [9,10] ])
ragged

<tf.RaggedTensor [[1, 2, 3, 4], [], [5, 6, 7], [8], [9, 10]]>

In [145]:
print(ragged)
print(ragged[0, :])
print(ragged[1, :])
print(ragged[2, :])
print(ragged[3, :])
print(ragged[4, :])

<tf.RaggedTensor [[1, 2, 3, 4], [], [5, 6, 7], [8], [9, 10]]>
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([5 6 7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([ 9 10], shape=(2,), dtype=int32)


# Finding squared difference between 2 tensors

In [146]:
# diff and then squared

x = [1,3,5,7,9]
y = 5

z = tf.math.squared_difference(x,y)
z

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 16], dtype=int32)>

NOTE: Here, the python variables , x and y, are cast into tensors and that y i s then broadcast across x in this example.

E.g: the first calculation is (1-5)^2 = 16

# Finding mean

*'tf.reduce_mean()'* is equivalent to np.mean, except that it infers the return datatype from the input tensor, whereas np.mean allows you to spicify the output type (default to float64):

```
tf.reduce_mean(input_tensor, axis= None, Keepdims= None, name= None)
```

In [147]:
num = tf.constant([ [1.,2.,3.], [4.,5.,6.] ])

### i.) Mean across all axes (use default axis = None)

In [148]:
tf.reduce_mean(input_tensor = num)

<tf.Tensor: shape=(), dtype=float32, numpy=3.5>

### ii.) Mean column-wise(i.e. reduce rows)

In [149]:
tf.reduce_mean(input_tensor = num, axis = 0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.5, 3.5, 4.5], dtype=float32)>

### iii.) When keepdims = True, the reduce axis is retained with a length of 1

The dimensions won't change even after the mean is calculated.

In [150]:
tf.reduce_mean(input_tensor = num, axis = 0, keepdims = True)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[2.5, 3.5, 4.5]], dtype=float32)>

In [151]:
num

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

### iv.) Mean row-wise(i.e. reduce columns)

In [152]:
tf.reduce_mean(input_tensor = num, axis = 1)
# (1+2+3)/3 = 2 and (4+5+6)/3 = 5

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

### v.) When keepdims = True, the reduce axis is retained with a length of 1

In [153]:
tf.reduce_mean(input_tensor = num, axis = 1, keepdims = True)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

## Generating tensors with random values

## 1.) *tf.random.normal()*
It gives a tensor of the given shape fileed with values of the data type from a normal distribution.

```
tf.random.normal(shape = (3,2), mean = 10, stdev = 2, dtype= tf.float32, seed = None)
```

In [154]:
tf.random.normal(shape = (3,2), mean = 10, stddev = 2, dtype = tf.float32, seed= None, name = None)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11.571223,  9.047942],
       [12.517892, 13.297017],
       [ 8.748987, 14.913409]], dtype=float32)>

In [155]:
ran = tf.random.normal(shape = (3,2), mean = 10.0, stddev = 2.0)
print(ran)

tf.Tensor(
[[10.0239525  9.939883 ]
 [ 7.615965   9.684287 ]
 [11.651227   8.022402 ]], shape=(3, 2), dtype=float32)


### 2.)*tf.random.uniform()*

It gives tensor of given shape filled with values from a uniform distribution in the range minval to maxval, where the lower bound is exclusive but the upper bound isn't.

```
tf.random.uniform(shape, minval = 0, maxval = None, dtype = tf.float64, seed = None, name = None)
```

In [156]:
tf.random.uniform(shape = (4,5), minval= 0, maxval = None, dtype=tf.float32, seed = None, name = None)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0.5413332 , 0.33799112, 0.01585352, 0.93062353, 0.5455812 ],
       [0.22052121, 0.05683291, 0.5539501 , 0.904762  , 0.4581194 ],
       [0.49991095, 0.13799798, 0.8336041 , 0.7827532 , 0.38813984],
       [0.09010267, 0.47759664, 0.532905  , 0.9187825 , 0.8928335 ]],
      dtype=float32)>

## Setting the seed

To get the same random values

In [157]:
tf.random.set_seed(11)

ran1 = tf.random.uniform(shape = (2,2), maxval = 10, dtype= tf.int32)
ran2 = tf.random.uniform(shape = (2,2), maxval = 10, dtype= tf.int32)

print(ran1)
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [158]:
tf.random.set_seed(11)

ran3 = tf.random.uniform(shape = (2,2), maxval = 10, dtype= tf.int32)
ran4 = tf.random.uniform(shape = (2,2), maxval = 10, dtype= tf.int32)

print(ran3)
print(ran4)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [159]:
tf.random.set_seed(12)

ran5 = tf.random.uniform(shape = (2,2), maxval = 10, dtype= tf.int32)
ran6 = tf.random.uniform(shape = (2,2), maxval = 10, dtype= tf.int32)

print(ran5)
print(ran6)

tf.Tensor(
[[2 2]
 [6 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[8 2]
 [2 2]], shape=(2, 2), dtype=int32)


Analysis:

1.) ran1 and ran2 are same as ran3 and ran4 respectively as the seed value is same(i.e. 11).

2.) ran5 and ran6 are differnt that ran1 and ran2 respectively as they have different seed value(i.e. 12).

# Practical example of random values using dices

In [160]:
dice1= tf.Variable(tf.random.uniform([10,1], minval= 1, maxval= 7, dtype= tf.int32))

dice2 = tf.Variable(tf.random.uniform([10,1], minval= 1, maxval= 7, dtype= tf.int32))

print("dice1", dice1)
print("\ndice2", dice2)

dice1 <tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[3],
       [3],
       [4],
       [1],
       [1],
       [4],
       [3],
       [2],
       [2],
       [4]], dtype=int32)>

dice2 <tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[6],
       [3],
       [6],
       [1],
       [6],
       [4],
       [6],
       [2],
       [1],
       [2]], dtype=int32)>


## Addition of dices

As dice1 and dice2 have same size and shape, we can ad them

In [161]:
dice3 = dice1 + dice2
dice3

<tf.Tensor: shape=(10, 1), dtype=int32, numpy=
array([[ 9],
       [ 6],
       [10],
       [ 2],
       [ 7],
       [ 8],
       [ 9],
       [ 4],
       [ 3],
       [ 6]], dtype=int32)>

## Analysis:

Now, we have 3 separate 10*1 matrices.

To produce a single 10*3 matrix, we will concatenate them along dimension 1.

In [162]:
res_matrix = tf.concat(values = [dice1, dice2, dice3], axis= 1)
print(res_matrix)

tf.Tensor(
[[ 3  6  9]
 [ 3  3  6]
 [ 4  6 10]
 [ 1  1  2]
 [ 1  6  7]
 [ 4  4  8]
 [ 3  6  9]
 [ 2  2  4]
 [ 2  1  3]
 [ 4  2  6]], shape=(10, 3), dtype=int32)


In [163]:
dice4 = tf.Variable(tf.random.uniform([5,1], minval= 1, maxval= 7, dtype= tf.int32))
dice5 = tf.concat(values= [res_matrix, dice4], axis= 1)
dice5

InvalidArgumentError: {{function_node __wrapped__ConcatV2_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ConcatOp : Dimension 0 in both shapes must be equal: shape[0] = [10,3] vs. shape[1] = [5,1] [Op:ConcatV2] name: concat

# Finding indices of the largest and smallest element

In [164]:
# 1-D tensor

t1= tf.constant([2, 11, 5, 200, 6, -6, -3, -100, 0])
print(t1)

tf.Tensor([   2   11    5  200    6   -6   -3 -100    0], shape=(9,), dtype=int32)


In [165]:
lar_ind = tf.argmax(input= t1)
print("Index of largest element-> ", lar_ind)
print("\nLargest element->", t1[lar_ind].numpy())

sml_ind = tf.argmin(input= t1)
print("Index of smallest element-> ", sml_ind)
print("\nSmallest element->", t1[sml_ind].numpy())

Index of largest element->  tf.Tensor(3, shape=(), dtype=int64)

Largest element-> 200
Index of smallest element->  tf.Tensor(7, shape=(), dtype=int64)

Smallest element-> -100


In [166]:
# 2-D tensor

t2= tf.reshape(t1, [3,3])
print(t2)

tf.Tensor(
[[   2   11    5]
 [ 200    6   -6]
 [  -3 -100    0]], shape=(3, 3), dtype=int32)


In [167]:
print("ROW-WISE")

lar_ind = tf.argmax(input= t2, axis= 0).numpy()
print("Index of largest element-> ", lar_ind)
#print("\nLargest element->", t1[lar_ind].numpy())

sml_ind = tf.argmin(input= t2, axis= 0).numpy()
print("Index of smallest element-> ", sml_ind)
#print("\nSmallest element->", t1[sml_ind].numpy())


ROW-WISE
Index of largest element->  [1 0 0]
Index of smallest element->  [2 2 1]


Explanation:

```
In t2 matrix, for ROW-WISE

ROW1-> max_ind= 1, min_ind= 2
ROW2-> max_ind= 0, min_ind= 2
ROW3-> max_ind= 0, min_ind= 1

max = [1,0,0], i.e. elements are [200, 11, 5]
min = [2,2,1], i.e. elements are [-3, -100, -6]
```

In [168]:
print(t2)

tf.Tensor(
[[   2   11    5]
 [ 200    6   -6]
 [  -3 -100    0]], shape=(3, 3), dtype=int32)


In [169]:
print("COLUMN-WISE")

lar_ind = tf.argmax(input= t2, axis= 1).numpy()
print("Index of largest element-> ", lar_ind)
#print("\nLargest element->", t1[lar_ind].numpy())

sml_ind = tf.argmin(input= t2, axis= 1).numpy()
print("Index of smallest element-> ", sml_ind)
#print("\nSmallest element->", t1[sml_ind].numpy())

COLUMN-WISE
Index of largest element->  [1 0 2]
Index of smallest element->  [0 2 1]


Explanation:

```
In t2 matrix, for COLUMN-WISE

COL1-> max_ind= 1, min_ind= 0  
COL2-> max_ind= 0, min_ind= 2
COL3-> max_ind= 2, min_ind= 1

max = [1,0,2], i.e. elements are [11, 200, 0]
min = [0,2,1], i.e. elements are [2, -6, -100]
```

# Saving and restoring tensor value using Checkpoint

In [170]:
var1 = tf.Variable([ [1,3,5,7], [100,300,500,700] ])
checkpoint = tf.train.Checkpoint(var= var1)
var1

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[  1,   3,   5,   7],
       [100, 300, 500, 700]], dtype=int32)>

In [171]:
save_path = checkpoint.save('./vars')
var1.assign( [ [0,0,0,0] ,[0,0,0,0] ] )
var1

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [172]:
checkpoint.restore(save_path)
var1

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[  1,   3,   5,   7],
       [100, 300, 500, 700]], dtype=int32)>

**NOTE:** The old matrix get restored using the checkpoint.

# Functions

*tf.function* is a fucntion that will that will take a python function and return a Tensorflow graph. The advantages of this is that graphs can apply optimizations and exploit parallelism in the Pyhton function(func).

*tf.function* is new to **Tensorflow 2**

```
tf.function(func= None, input_signature= None, autograph= True, experimental_autograph_options= None)
```

In [173]:
def f1(x,y):
  return tf.reduce_mean(input_tensor = tf.multiply(x**2, 5) + y**2)

f2 = tf.function(f1)
x = tf.constant([4,-5])
y = tf.constant([2,3])

assert f1(x,y).numpy() == f2(x,y).numpy()   # the assrt passes,so there is no O/P

**NOTE:** f1 and f2 return the same value but f2 executes as a Tensorflow graph.

# Calculate the gradient

##Gradient Tape:

Another difference from Numpy is that it can automatically track the gradient of any variable.

Open one Gradient Tape and tape.watch() track varaibles through.

In [174]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
  tape.watch(a)
  c = tf.sqrt(tf.square(a) + tf.square(b))
  dc_da = tape.gradient(c,a)
  print(dc_da)

# It gives partial differentiation of function 'c' w.r.t var 'a'.

tf.Tensor(
[[ 0.8503445  -0.06113244]
 [-0.7449737  -0.40131947]], shape=(2, 2), dtype=float32)


Note: For all varaibles, the calculation is tracked by default and used to find the gradient, so do not use ```tape.watch()```.

In [175]:
# Another method to write the above

a_new = tf.Variable(a)

with tf.GradientTape() as tape:
  c = tf.sqrt(tf.square(a_new) + tf.square(b))
  dc_da = tape.gradient(c, a_new)
  print(dc_da)

# We can see that here, if we take "a" as a variable, then there is no need to use tape.watch(a).

tf.Tensor(
[[ 0.8503445  -0.06113244]
 [-0.7449737  -0.40131947]], shape=(2, 2), dtype=float32)


### GradientTape to find higher order derivatives by opening a few more.

In [176]:
a = tf.Variable(a)

with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a) + tf.square(b))
    dc_da = tape.gradient(c,a)
  d2c_da2 = outer_tape.gradient(dc_da,a)

  print(d2c_da2)


tf.Tensor(
[[0.41935146 0.9715245 ]
 [0.1766931  0.72649866]], shape=(2, 2), dtype=float32)
